debug: false
parent:
  redis:
    enabled: true

management:
  health:
    redis:
      enabled: false

server:
  port: 8083

spring:
  datasource:
    url: jdbc:mysql://172.16.202.40:3306/testdb1?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  redis:
    host: 172.16.202.40
    port: 6379
    database: 8
    password:

  dubbo:
    application:
      name: parent-demo-zjx
    registry: zookeeper://172.16.202.33:2181?backup=172.16.202.40:2181
    protocol: dubbo

  rabbitmq:
    virtual-host: /
    addresses: 172.16.202.40:5672
    host: 172.16.202.40
    port: 5672
    username: zhangjiaxing
    password: 123456
    queue: queue1
    exchange: fanout-test

myserver:
  ons:
    consumer-id: CID_schoolFeeds_debug
    product-id: PID_schoolFeeds_debug
    access-key: 06xxZ11yge6LekDx
    secret-key: PMbyrM2DZC3QIu586BTyGQCBS5l3nt